use std::path::{Path, PathBuf};

fn main() {
    // --- Existing: PIANO_RUNTIME_VERSION ---
    let runtime_cargo = Path::new("piano-runtime").join("Cargo.toml");
    println!("cargo::rerun-if-changed={}", runtime_cargo.display());

    let version = match std::fs::read_to_string(&runtime_cargo) {
        Ok(contents) => contents
            .parse::<toml_edit::DocumentMut>()
            .expect("failed to parse piano-runtime/Cargo.toml")
            .get("package")
            .and_then(|p| p.get("version"))
            .and_then(|v| v.as_str())
            .expect("missing [package].version in piano-runtime/Cargo.toml")
            .to_owned(),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            // When installed from crates.io the workspace sibling is absent;
            // fall back to the CLI package version (kept in sync at publish time).
            std::env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION not set")
        }
        Err(e) => {
            panic!("failed to read piano-runtime/Cargo.toml: {e}");
        }
    };

    println!("cargo::rustc-env=PIANO_RUNTIME_VERSION={version}");

    // --- New: embed runtime source ---
    let runtime_dir = if Path::new("piano-runtime/src/lib.rs").exists() {
        PathBuf::from("piano-runtime")
    } else if Path::new("runtime-src/src/lib.rs").exists() {
        PathBuf::from("runtime-src")
    } else {
        // When neither exists (shouldn't happen in normal builds),
        // skip embedding. The wrapper will error at runtime if needed.
        return;
    };

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
    let embed_dir = out_dir.join("runtime_embed");

    // Collect all files to embed
    let mut files: Vec<(String, PathBuf)> = Vec::new();

    // Cargo.toml (with [workspace] injected)
    let cargo_toml_src = runtime_dir.join("Cargo.toml");
    std::fs::create_dir_all(embed_dir.join("src")).unwrap();
    let mut cargo_content = std::fs::read_to_string(&cargo_toml_src).unwrap();
    // Strip [[bench]], [dev-dependencies], and [[test]] sections -- these reference
    // files that aren't embedded and would cause the build to fail.
    let mut doc: toml_edit::DocumentMut = cargo_content.parse().unwrap();
    doc.remove("bench");
    doc.remove("dev-dependencies");
    doc.remove("test");
    cargo_content = doc.to_string();
    if !cargo_content.contains("[workspace]") {
        cargo_content.push_str("\n[workspace]\n");
    }
    let cargo_toml_dst = embed_dir.join("Cargo.toml");
    std::fs::write(&cargo_toml_dst, &cargo_content).unwrap();
    println!("cargo::rerun-if-changed={}", cargo_toml_src.display());
    files.push(("Cargo.toml".to_string(), cargo_toml_dst));

    // Source files
    for entry in walkdir::WalkDir::new(runtime_dir.join("src"))
        .into_iter()
        .filter_map(|e| e.ok())
    {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        let Some(ext) = path.extension() else {
            continue;
        };
        if ext != "rs" {
            continue;
        }
        let rel = path.strip_prefix(&runtime_dir).unwrap();
        let dst = embed_dir.join(rel);
        if let Some(parent) = dst.parent() {
            std::fs::create_dir_all(parent).unwrap();
        }
        std::fs::copy(path, &dst).unwrap();
        println!("cargo::rerun-if-changed={}", path.display());
        files.push((rel.to_string_lossy().to_string(), dst));
    }

    // Sort for deterministic output
    files.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate the embed module
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs -- do not edit\n\n");

    // Constants
    for (rel, _dst) in &files {
        let const_name = rel.replace(['/', '.'], "_").to_uppercase();
        let embed_rel = format!("runtime_embed/{rel}");
        code.push_str(&format!(
            "pub const {const_name}: &str = include_str!(concat!(env!(\"OUT_DIR\"), \"/{embed_rel}\"));\n"
        ));
    }

    // files() function
    code.push_str("\npub fn files() -> &'static [(&'static str, &'static str)] {\n");
    code.push_str("    &[\n");
    for (rel, _dst) in &files {
        let const_name = rel.replace(['/', '.'], "_").to_uppercase();
        code.push_str(&format!("        (\"{rel}\", {const_name}),\n"));
    }
    code.push_str("    ]\n}\n");

    std::fs::write(out_dir.join("runtime_embed.rs"), code).unwrap();
}
