use std::path::{Path, PathBuf};

fn main() {
    // --- Existing: PIANO_RUNTIME_VERSION ---
    let runtime_cargo = Path::new("piano-runtime").join("Cargo.toml");
    println!("cargo::rerun-if-changed={}", runtime_cargo.display());

    let version = match std::fs::read_to_string(&runtime_cargo) {
        Ok(contents) => contents
            .parse::<toml_edit::DocumentMut>()
            .expect("failed to parse piano-runtime/Cargo.toml")
            .get("package")
            .and_then(|p| p.get("version"))
            .and_then(|v| v.as_str())
            .expect("missing [package].version in piano-runtime/Cargo.toml")
            .to_owned(),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
            // When installed from crates.io the workspace sibling is absent;
            // fall back to the CLI package version (kept in sync at publish time).
            std::env::var("CARGO_PKG_VERSION").expect("CARGO_PKG_VERSION not set")
        }
        Err(e) => {
            panic!("failed to read piano-runtime/Cargo.toml: {e}");
        }
    };

    println!("cargo::rustc-env=PIANO_RUNTIME_VERSION={version}");

    // --- Embed runtime source ---
    // In workspace builds, piano-runtime/ is the workspace sibling.
    // In crates.io packages, runtime-src/ holds a copy (Cargo.toml renamed
    // to Cargo.toml.embed so cargo doesn't auto-detect it as a package).
    let (runtime_dir, cargo_toml_name) = if Path::new("piano-runtime/src/lib.rs").exists() {
        (PathBuf::from("piano-runtime"), "Cargo.toml")
    } else if Path::new("runtime-src/src/lib.rs").exists() {
        (PathBuf::from("runtime-src"), "Cargo.toml.embed")
    } else {
        // Neither exists — generate a stub so src/runtime_embed.rs compiles.
        // This only happens during cargo publish verification (the actual
        // published tarball includes runtime-src/).
        let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());
        std::fs::write(
            out_dir.join("runtime_embed.rs"),
            "pub fn files() -> &'static [(&'static str, &'static str)] { &[] }\n",
        )
        .unwrap();
        return;
    };

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    // Collect all files to embed
    let mut files: Vec<(String, String)> = Vec::new();

    // Cargo.toml (with [workspace] injected)
    let cargo_toml_src = runtime_dir.join(cargo_toml_name);
    let mut cargo_content = std::fs::read_to_string(&cargo_toml_src).unwrap();
    // Strip [[bench]], [dev-dependencies], and [[test]] sections -- these reference
    // files that aren't embedded and would cause the build to fail.
    let mut doc: toml_edit::DocumentMut = cargo_content.parse().unwrap();
    doc.remove("bench");
    doc.remove("dev-dependencies");
    doc.remove("test");
    cargo_content = doc.to_string();
    if !cargo_content.contains("[workspace]") {
        cargo_content.push_str("\n[workspace]\n");
    }
    println!("cargo::rerun-if-changed={}", cargo_toml_src.display());
    files.push(("Cargo.toml".to_string(), cargo_content));

    // Source files
    for entry in walkdir::WalkDir::new(runtime_dir.join("src"))
        .into_iter()
        .filter_map(|e| e.ok())
    {
        if !entry.file_type().is_file() {
            continue;
        }
        let path = entry.path();
        let Some(ext) = path.extension() else {
            continue;
        };
        if ext != "rs" {
            continue;
        }
        let rel = path
            .strip_prefix(&runtime_dir)
            .unwrap()
            .to_string_lossy()
            .to_string();
        let content = std::fs::read_to_string(path).unwrap();
        println!("cargo::rerun-if-changed={}", path.display());
        files.push((rel, content));
    }

    // Sort for deterministic output
    files.sort_by(|a, b| a.0.cmp(&b.0));

    // Generate the embed module with content inlined as string literals.
    // This makes the generated file self-contained -- rustc doesn't need
    // access to the original source files.
    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs -- do not edit\n\n");
    code.push_str("pub fn files() -> &'static [(&'static str, &'static str)] {\n");
    code.push_str("    &[\n");
    for (rel, content) in &files {
        code.push_str(&format!("        (\"{rel}\", r####\"{content}\"####),\n"));
    }
    code.push_str("    ]\n}\n");

    std::fs::write(out_dir.join("runtime_embed.rs"), code).unwrap();
}
