// Code generated by carve-build. DO NOT EDIT.

// Copyright (C) 2026 Harnoor Lal
//
// This program is free software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation, version 3 of
// the License.
//
// This program is distributed in the hope that it will be
// useful, but WITHOUT ANY WARRANTY; without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
// PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public
// License along with this program.  If not, see
// <https://www.gnu.org/licenses/>.

// As a special exception, you may create a larger work that
// contains part or all of the text that carve copies from its
// own code (not from its input file) into its output files and
// distribute that work under terms of your choice, so long as
// that work isn't itself a code generator using that text or a
// modified version thereof as text that it copies into its
// output.  Alternatively, if you modify or redistribute carve
// itself, you may (at your option) remove this special
// exception, which will cause that text and the resulting
// carve output files to be licensed under the GNU General
// Public License without this special exception.
//
// This special exception was added by Harnoor Lal in version
// 0.1.0 of carve.
//
// This Exception is an additional permission under section 7
// of the GNU General Public License, version 3 ("GPLv3").

#![cfg_attr(rustfmt, rustfmt::skip)]

// External binding preserves the declared name for type slots.
#[allow(unused_imports)]
pub use crate::output::NameTable;

pub mod piano_runtime {

pub mod ticks {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Ticks(u64);

    impl Ticks {
        pub(crate) fn new(inner: u64) -> Self { Self(inner) }
        pub fn value(&self) -> u64 { self.0 }
    }
}

pub mod wall_ns {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct WallNs(u64);

    impl WallNs {
        pub(crate) fn new(inner: u64) -> Self { Self(inner) }
        pub fn value(&self) -> u64 { self.0 }
    }
}

pub mod cpu_ns {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct CpuNs(u64);

    impl CpuNs {
        pub(crate) fn new(inner: u64) -> Self { Self(inner) }
        pub fn value(&self) -> u64 { self.0 }
    }
}

pub mod alloc_snapshot {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct AllocSnapshot {
        alloc_count: u64,
        alloc_bytes: u64,
        free_count: u64,
        free_bytes: u64,
    }

    impl AllocSnapshot {
        fn new(alloc_count: u64, alloc_bytes: u64, free_count: u64, free_bytes: u64) -> Self { Self { alloc_count, alloc_bytes, free_count, free_bytes } }
        pub fn alloc_count(&self) -> u64 { self.alloc_count }
        pub fn alloc_bytes(&self) -> u64 { self.alloc_bytes }
        pub fn free_count(&self) -> u64 { self.free_count }
        pub fn free_bytes(&self) -> u64 { self.free_bytes }
    }

pub mod snapshot {
    /// is_snapshot(v)
    ///
    /// Produced by: snapshot_counter() -> Snapshot
    /// Consumed by: compute_delta (observed)
    #[derive(Debug)]
    pub struct Snapshot {
        alloc_count: u64,
        alloc_bytes: u64,
        free_count: u64,
        free_bytes: u64,
    }

    impl Snapshot {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(alloc_count: u64, alloc_bytes: u64, free_count: u64, free_bytes: u64) -> Self { Self { alloc_count, alloc_bytes, free_count, free_bytes } }
        pub fn alloc_count(&self) -> u64 { self.alloc_count }
        pub fn alloc_bytes(&self) -> u64 { self.alloc_bytes }
        pub fn free_count(&self) -> u64 { self.free_count }
        pub fn free_bytes(&self) -> u64 { self.free_bytes }
    }
}

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn() -> crate::AllocSnapshot = ops::snapshot_counter;
}

pub mod alloc_delta {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct AllocDelta {
        alloc_count: u64,
        alloc_bytes: u64,
        free_count: u64,
        free_bytes: u64,
    }

    impl AllocDelta {
        fn new(alloc_count: u64, alloc_bytes: u64, free_count: u64, free_bytes: u64) -> Self { Self { alloc_count, alloc_bytes, free_count, free_bytes } }
        pub fn alloc_count(&self) -> u64 { self.alloc_count }
        pub fn alloc_bytes(&self) -> u64 { self.alloc_bytes }
        pub fn free_count(&self) -> u64 { self.free_count }
        pub fn free_bytes(&self) -> u64 { self.free_bytes }
    }

pub mod delta {
    /// is_delta(v)
    ///
    /// Produced by: compute_delta(end: &AllocSnapshot, start: &AllocSnapshot) -> Delta
    /// Produced by: accumulate_delta(acc: &AllocDelta, delta: &AllocDelta) -> Delta
    /// Consumed by: accumulate_delta (observed)
    /// Consumed by: aggregate (observed)
    /// Consumed by: serialize_aggregate (observed)
    #[derive(Debug)]
    pub struct Delta {
        alloc_count: u64,
        alloc_bytes: u64,
        free_count: u64,
        free_bytes: u64,
    }

    impl Delta {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(alloc_count: u64, alloc_bytes: u64, free_count: u64, free_bytes: u64) -> Self { Self { alloc_count, alloc_bytes, free_count, free_bytes } }
        pub fn alloc_count(&self) -> u64 { self.alloc_count }
        pub fn alloc_bytes(&self) -> u64 { self.alloc_bytes }
        pub fn free_count(&self) -> u64 { self.free_count }
        pub fn free_bytes(&self) -> u64 { self.free_bytes }
    }
}

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(end: &crate::AllocSnapshot, start: &crate::AllocSnapshot) -> crate::AllocDelta = ops::compute_delta;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(acc: &crate::AllocDelta, delta: &crate::AllocDelta) -> crate::AllocDelta = ops::accumulate_delta;
}

pub mod name_id {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct NameId(u32);

    impl NameId {
        pub fn new(inner: u32) -> Self { Self(inner) }
        pub fn value(&self) -> u32 { self.0 }
    }
}

pub mod sync_execution {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct SyncExecution {
        name_id: super::super::piano_runtime::name_id::NameId,
        start_ticks: super::super::piano_runtime::ticks::Ticks,
        cpu_start: super::super::piano_runtime::cpu_ns::CpuNs,
        alloc_start: super::super::piano_runtime::alloc_snapshot::AllocSnapshot,
        saved_children_ns: super::super::piano_runtime::wall_ns::WallNs,
    }

    impl SyncExecution {
        fn new(name_id: super::super::piano_runtime::name_id::NameId, start_ticks: super::super::piano_runtime::ticks::Ticks, cpu_start: super::super::piano_runtime::cpu_ns::CpuNs, alloc_start: super::super::piano_runtime::alloc_snapshot::AllocSnapshot, saved_children_ns: super::super::piano_runtime::wall_ns::WallNs) -> Self { Self { name_id, start_ticks, cpu_start, alloc_start, saved_children_ns } }
        pub fn name_id(&self) -> &super::super::piano_runtime::name_id::NameId { &self.name_id }
        pub fn start_ticks(&self) -> &super::super::piano_runtime::ticks::Ticks { &self.start_ticks }
        pub fn cpu_start(&self) -> &super::super::piano_runtime::cpu_ns::CpuNs { &self.cpu_start }
        pub fn alloc_start(&self) -> &super::super::piano_runtime::alloc_snapshot::AllocSnapshot { &self.alloc_start }
        pub fn saved_children_ns(&self) -> &super::super::piano_runtime::wall_ns::WallNs { &self.saved_children_ns }
    }

pub mod entered {
    /// is_entered(v)
    ///
    /// Produced by: enter_sync(id: &NameId) -> Entered
    /// Consumed by: exit_sync (consumed)
    #[derive(Debug)]
    pub struct Entered {
        name_id: super::super::super::piano_runtime::name_id::NameId,
        start_ticks: super::super::super::piano_runtime::ticks::Ticks,
        cpu_start: super::super::super::piano_runtime::cpu_ns::CpuNs,
        alloc_start: super::super::super::piano_runtime::alloc_snapshot::AllocSnapshot,
        saved_children_ns: super::super::super::piano_runtime::wall_ns::WallNs,
    }

    impl Entered {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(name_id: super::super::super::piano_runtime::name_id::NameId, start_ticks: super::super::super::piano_runtime::ticks::Ticks, cpu_start: super::super::super::piano_runtime::cpu_ns::CpuNs, alloc_start: super::super::super::piano_runtime::alloc_snapshot::AllocSnapshot, saved_children_ns: super::super::super::piano_runtime::wall_ns::WallNs) -> Self { Self { name_id, start_ticks, cpu_start, alloc_start, saved_children_ns } }
        pub fn name_id(&self) -> &super::super::super::piano_runtime::name_id::NameId { &self.name_id }
        pub fn start_ticks(&self) -> &super::super::super::piano_runtime::ticks::Ticks { &self.start_ticks }
        pub fn cpu_start(&self) -> &super::super::super::piano_runtime::cpu_ns::CpuNs { &self.cpu_start }
        pub fn alloc_start(&self) -> &super::super::super::piano_runtime::alloc_snapshot::AllocSnapshot { &self.alloc_start }
        pub fn saved_children_ns(&self) -> &super::super::super::piano_runtime::wall_ns::WallNs { &self.saved_children_ns }
    }
}

pub mod exited {
    /// is_exited(v)
    ///
    /// Produced by: exit_sync(exec: SyncExecution) -> Exited
    #[derive(Debug)]
    pub struct Exited {
        name_id: super::super::super::piano_runtime::name_id::NameId,
        start_ticks: super::super::super::piano_runtime::ticks::Ticks,
        cpu_start: super::super::super::piano_runtime::cpu_ns::CpuNs,
        alloc_start: super::super::super::piano_runtime::alloc_snapshot::AllocSnapshot,
    }

    impl Exited {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(name_id: super::super::super::piano_runtime::name_id::NameId, start_ticks: super::super::super::piano_runtime::ticks::Ticks, cpu_start: super::super::super::piano_runtime::cpu_ns::CpuNs, alloc_start: super::super::super::piano_runtime::alloc_snapshot::AllocSnapshot) -> Self { Self { name_id, start_ticks, cpu_start, alloc_start } }
        pub fn name_id(&self) -> &super::super::super::piano_runtime::name_id::NameId { &self.name_id }
        pub fn start_ticks(&self) -> &super::super::super::piano_runtime::ticks::Ticks { &self.start_ticks }
        pub fn cpu_start(&self) -> &super::super::super::piano_runtime::cpu_ns::CpuNs { &self.cpu_start }
        pub fn alloc_start(&self) -> &super::super::super::piano_runtime::alloc_snapshot::AllocSnapshot { &self.alloc_start }
    }
}

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(id: &crate::NameId) -> crate::generated::piano_runtime::sync_execution::SyncExecution = ops::enter_sync;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(exec: crate::generated::piano_runtime::sync_execution::SyncExecution) -> crate::generated::piano_runtime::sync_execution::SyncExecution = ops::exit_sync;
}

pub mod async_execution {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct AsyncExecution {
        name_id: super::super::piano_runtime::name_id::NameId,
        wall_acc: Option<super::super::piano_runtime::wall_ns::WallNs>,
        cpu_acc: super::super::piano_runtime::cpu_ns::CpuNs,
        alloc_acc: super::super::piano_runtime::alloc_delta::AllocDelta,
        children_ns_acc: super::super::piano_runtime::wall_ns::WallNs,
        emitted: bool,
    }

    impl AsyncExecution {
        fn new(name_id: super::super::piano_runtime::name_id::NameId, wall_acc: Option<super::super::piano_runtime::wall_ns::WallNs>, cpu_acc: super::super::piano_runtime::cpu_ns::CpuNs, alloc_acc: super::super::piano_runtime::alloc_delta::AllocDelta, children_ns_acc: super::super::piano_runtime::wall_ns::WallNs, emitted: bool) -> Self { Self { name_id, wall_acc, cpu_acc, alloc_acc, children_ns_acc, emitted } }
        pub fn name_id(&self) -> &super::super::piano_runtime::name_id::NameId { &self.name_id }
        pub fn wall_acc(&self) -> &Option<super::super::piano_runtime::wall_ns::WallNs> { &self.wall_acc }
        pub fn cpu_acc(&self) -> &super::super::piano_runtime::cpu_ns::CpuNs { &self.cpu_acc }
        pub fn alloc_acc(&self) -> &super::super::piano_runtime::alloc_delta::AllocDelta { &self.alloc_acc }
        pub fn children_ns_acc(&self) -> &super::super::piano_runtime::wall_ns::WallNs { &self.children_ns_acc }
        pub fn emitted(&self) -> bool { self.emitted }
    }

pub mod ever_polled {
    /// is_ever_polled(v)
    ///
    /// Consumed by: emit (observed)
    #[derive(Debug)]
    pub struct EverPolled {
        name_id: super::super::super::piano_runtime::name_id::NameId,
        wall_acc: Option<super::super::super::piano_runtime::wall_ns::WallNs>,
        cpu_acc: super::super::super::piano_runtime::cpu_ns::CpuNs,
        alloc_acc: super::super::super::piano_runtime::alloc_delta::AllocDelta,
        children_ns_acc: super::super::super::piano_runtime::wall_ns::WallNs,
        emitted: bool,
    }

    impl EverPolled {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(name_id: super::super::super::piano_runtime::name_id::NameId, wall_acc: Option<super::super::super::piano_runtime::wall_ns::WallNs>, cpu_acc: super::super::super::piano_runtime::cpu_ns::CpuNs, alloc_acc: super::super::super::piano_runtime::alloc_delta::AllocDelta, children_ns_acc: super::super::super::piano_runtime::wall_ns::WallNs, emitted: bool) -> Self { Self { name_id, wall_acc, cpu_acc, alloc_acc, children_ns_acc, emitted } }
        pub fn name_id(&self) -> &super::super::super::piano_runtime::name_id::NameId { &self.name_id }
        pub fn wall_acc(&self) -> &Option<super::super::super::piano_runtime::wall_ns::WallNs> { &self.wall_acc }
        pub fn cpu_acc(&self) -> &super::super::super::piano_runtime::cpu_ns::CpuNs { &self.cpu_acc }
        pub fn alloc_acc(&self) -> &super::super::super::piano_runtime::alloc_delta::AllocDelta { &self.alloc_acc }
        pub fn children_ns_acc(&self) -> &super::super::super::piano_runtime::wall_ns::WallNs { &self.children_ns_acc }
        pub fn emitted(&self) -> bool { self.emitted }
    }
}

pub mod ever_polled_idle {
    /// and(is_ever_polled(v),is_idle(v))
    ///
    /// Produced by: end_poll(exec: MidPoll) -> EverPolledIdle
    /// Consumed by: mark_completed (consumed)
    #[derive(Debug)]
    pub struct EverPolledIdle {
        name_id: super::super::super::piano_runtime::name_id::NameId,
        wall_acc: Option<super::super::super::piano_runtime::wall_ns::WallNs>,
        cpu_acc: super::super::super::piano_runtime::cpu_ns::CpuNs,
        alloc_acc: super::super::super::piano_runtime::alloc_delta::AllocDelta,
        children_ns_acc: super::super::super::piano_runtime::wall_ns::WallNs,
        emitted: bool,
    }

    impl EverPolledIdle {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(name_id: super::super::super::piano_runtime::name_id::NameId, wall_acc: Option<super::super::super::piano_runtime::wall_ns::WallNs>, cpu_acc: super::super::super::piano_runtime::cpu_ns::CpuNs, alloc_acc: super::super::super::piano_runtime::alloc_delta::AllocDelta, children_ns_acc: super::super::super::piano_runtime::wall_ns::WallNs, emitted: bool) -> Self { Self { name_id, wall_acc, cpu_acc, alloc_acc, children_ns_acc, emitted } }
        pub fn name_id(&self) -> &super::super::super::piano_runtime::name_id::NameId { &self.name_id }
        pub fn wall_acc(&self) -> &Option<super::super::super::piano_runtime::wall_ns::WallNs> { &self.wall_acc }
        pub fn cpu_acc(&self) -> &super::super::super::piano_runtime::cpu_ns::CpuNs { &self.cpu_acc }
        pub fn alloc_acc(&self) -> &super::super::super::piano_runtime::alloc_delta::AllocDelta { &self.alloc_acc }
        pub fn children_ns_acc(&self) -> &super::super::super::piano_runtime::wall_ns::WallNs { &self.children_ns_acc }
        pub fn emitted(&self) -> bool { self.emitted }
    }
}

pub mod idle {
    /// is_idle(v)
    ///
    /// Produced by: create_async(id: &NameId) -> Idle
    /// Consumed by: begin_poll (consumed)
    #[derive(Debug)]
    pub struct Idle {
        name_id: super::super::super::piano_runtime::name_id::NameId,
        wall_acc: Option<super::super::super::piano_runtime::wall_ns::WallNs>,
        cpu_acc: super::super::super::piano_runtime::cpu_ns::CpuNs,
        alloc_acc: super::super::super::piano_runtime::alloc_delta::AllocDelta,
        children_ns_acc: super::super::super::piano_runtime::wall_ns::WallNs,
        emitted: bool,
    }

    impl Idle {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(name_id: super::super::super::piano_runtime::name_id::NameId, wall_acc: Option<super::super::super::piano_runtime::wall_ns::WallNs>, cpu_acc: super::super::super::piano_runtime::cpu_ns::CpuNs, alloc_acc: super::super::super::piano_runtime::alloc_delta::AllocDelta, children_ns_acc: super::super::super::piano_runtime::wall_ns::WallNs, emitted: bool) -> Self { Self { name_id, wall_acc, cpu_acc, alloc_acc, children_ns_acc, emitted } }
        pub fn name_id(&self) -> &super::super::super::piano_runtime::name_id::NameId { &self.name_id }
        pub fn wall_acc(&self) -> &Option<super::super::super::piano_runtime::wall_ns::WallNs> { &self.wall_acc }
        pub fn cpu_acc(&self) -> &super::super::super::piano_runtime::cpu_ns::CpuNs { &self.cpu_acc }
        pub fn alloc_acc(&self) -> &super::super::super::piano_runtime::alloc_delta::AllocDelta { &self.alloc_acc }
        pub fn children_ns_acc(&self) -> &super::super::super::piano_runtime::wall_ns::WallNs { &self.children_ns_acc }
        pub fn emitted(&self) -> bool { self.emitted }
    }
}

pub mod mid_poll {
    /// is_mid_poll(v)
    ///
    /// Produced by: begin_poll(exec: AsyncExecution) -> MidPoll
    /// Consumed by: end_poll (consumed)
    #[derive(Debug)]
    pub struct MidPoll {
        name_id: super::super::super::piano_runtime::name_id::NameId,
        wall_acc: Option<super::super::super::piano_runtime::wall_ns::WallNs>,
        cpu_acc: super::super::super::piano_runtime::cpu_ns::CpuNs,
        alloc_acc: super::super::super::piano_runtime::alloc_delta::AllocDelta,
        children_ns_acc: super::super::super::piano_runtime::wall_ns::WallNs,
        emitted: bool,
        poll_start_ticks: super::super::super::piano_runtime::ticks::Ticks,
        poll_cpu_start: super::super::super::piano_runtime::cpu_ns::CpuNs,
        poll_alloc_start: super::super::super::piano_runtime::alloc_snapshot::AllocSnapshot,
        poll_children_saved: super::super::super::piano_runtime::wall_ns::WallNs,
    }

    impl MidPoll {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        // Constructor mirrors the product fields exactly.
        #[allow(clippy::too_many_arguments)]
        pub(crate) fn new(name_id: super::super::super::piano_runtime::name_id::NameId, wall_acc: Option<super::super::super::piano_runtime::wall_ns::WallNs>, cpu_acc: super::super::super::piano_runtime::cpu_ns::CpuNs, alloc_acc: super::super::super::piano_runtime::alloc_delta::AllocDelta, children_ns_acc: super::super::super::piano_runtime::wall_ns::WallNs, emitted: bool, poll_start_ticks: super::super::super::piano_runtime::ticks::Ticks, poll_cpu_start: super::super::super::piano_runtime::cpu_ns::CpuNs, poll_alloc_start: super::super::super::piano_runtime::alloc_snapshot::AllocSnapshot, poll_children_saved: super::super::super::piano_runtime::wall_ns::WallNs) -> Self { Self { name_id, wall_acc, cpu_acc, alloc_acc, children_ns_acc, emitted, poll_start_ticks, poll_cpu_start, poll_alloc_start, poll_children_saved } }
        pub fn name_id(&self) -> &super::super::super::piano_runtime::name_id::NameId { &self.name_id }
        pub fn wall_acc(&self) -> &Option<super::super::super::piano_runtime::wall_ns::WallNs> { &self.wall_acc }
        pub fn cpu_acc(&self) -> &super::super::super::piano_runtime::cpu_ns::CpuNs { &self.cpu_acc }
        pub fn alloc_acc(&self) -> &super::super::super::piano_runtime::alloc_delta::AllocDelta { &self.alloc_acc }
        pub fn children_ns_acc(&self) -> &super::super::super::piano_runtime::wall_ns::WallNs { &self.children_ns_acc }
        pub fn emitted(&self) -> bool { self.emitted }
        pub fn poll_start_ticks(&self) -> &super::super::super::piano_runtime::ticks::Ticks { &self.poll_start_ticks }
        pub fn poll_cpu_start(&self) -> &super::super::super::piano_runtime::cpu_ns::CpuNs { &self.poll_cpu_start }
        pub fn poll_alloc_start(&self) -> &super::super::super::piano_runtime::alloc_snapshot::AllocSnapshot { &self.poll_alloc_start }
        pub fn poll_children_saved(&self) -> &super::super::super::piano_runtime::wall_ns::WallNs { &self.poll_children_saved }
    }
}

pub mod poll_completed {
    /// is_poll_completed(v)
    ///
    /// Produced by: mark_completed(exec: AsyncExecution) -> PollCompleted
    #[derive(Debug)]
    pub struct PollCompleted {
        name_id: super::super::super::piano_runtime::name_id::NameId,
        wall_acc: Option<super::super::super::piano_runtime::wall_ns::WallNs>,
        cpu_acc: super::super::super::piano_runtime::cpu_ns::CpuNs,
        alloc_acc: super::super::super::piano_runtime::alloc_delta::AllocDelta,
        children_ns_acc: super::super::super::piano_runtime::wall_ns::WallNs,
        emitted: bool,
    }

    impl PollCompleted {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(name_id: super::super::super::piano_runtime::name_id::NameId, wall_acc: Option<super::super::super::piano_runtime::wall_ns::WallNs>, cpu_acc: super::super::super::piano_runtime::cpu_ns::CpuNs, alloc_acc: super::super::super::piano_runtime::alloc_delta::AllocDelta, children_ns_acc: super::super::super::piano_runtime::wall_ns::WallNs, emitted: bool) -> Self { Self { name_id, wall_acc, cpu_acc, alloc_acc, children_ns_acc, emitted } }
        pub fn name_id(&self) -> &super::super::super::piano_runtime::name_id::NameId { &self.name_id }
        pub fn wall_acc(&self) -> &Option<super::super::super::piano_runtime::wall_ns::WallNs> { &self.wall_acc }
        pub fn cpu_acc(&self) -> &super::super::super::piano_runtime::cpu_ns::CpuNs { &self.cpu_acc }
        pub fn alloc_acc(&self) -> &super::super::super::piano_runtime::alloc_delta::AllocDelta { &self.alloc_acc }
        pub fn children_ns_acc(&self) -> &super::super::super::piano_runtime::wall_ns::WallNs { &self.children_ns_acc }
        pub fn emitted(&self) -> bool { self.emitted }
    }
}

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(id: &crate::NameId) -> crate::generated::piano_runtime::async_execution::AsyncExecution = ops::create_async;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(exec: crate::MidPoll) -> crate::generated::piano_runtime::async_execution::AsyncExecution = ops::end_poll;
}

pub mod interrupted_entry {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct InterruptedEntry {
        name_id: super::super::piano_runtime::name_id::NameId,
        start_ticks: super::super::piano_runtime::ticks::Ticks,
        depth: u32,
    }

    impl InterruptedEntry {
        fn new(name_id: super::super::piano_runtime::name_id::NameId, start_ticks: super::super::piano_runtime::ticks::Ticks, depth: u32) -> Self { Self { name_id, start_ticks, depth } }
        pub fn name_id(&self) -> &super::super::piano_runtime::name_id::NameId { &self.name_id }
        pub fn start_ticks(&self) -> &super::super::piano_runtime::ticks::Ticks { &self.start_ticks }
        pub fn depth(&self) -> u32 { self.depth }
    }

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(id: &crate::NameId, start: &crate::Ticks, depth: u32) -> crate::InterruptedEntry = ops::interrupt_execution;
}

pub mod serialized_line {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct SerializedLine(String);

    impl SerializedLine {
        pub(crate) fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }

pub mod aggregate_line {
    /// is_aggregate_line(v)
    ///
    /// Produced by: serialize_aggregate(id: &NameId, self_wall: &WallNs, inclusive_wall: &WallNs, cpu_self: &CpuNs, alloc: &AllocDelta, calls: u64, thread: u64) -> AggregateLine
    #[derive(Clone, Debug)]
    pub struct AggregateLine(String);

    impl AggregateLine {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }
}

pub mod header_line {
    /// is_header_line(v)
    ///
    /// Produced by: serialize_header(names: &NameTable, bias: &WallNs, cpu_bias: &CpuNs, run_id: &String, timestamp_ms: u128) -> HeaderLine
    #[derive(Clone, Debug)]
    pub struct HeaderLine(String);

    impl HeaderLine {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }
}

pub mod interrupted_line {
    /// is_interrupted_line(v)
    ///
    /// Produced by: serialize_interrupted(id: &NameId, elapsed: &WallNs, depth: u32) -> InterruptedLine
    #[derive(Clone, Debug)]
    pub struct InterruptedLine(String);

    impl InterruptedLine {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }
}

pub mod serialized {
    /// is_serialized(v)
    ///
    /// Consumed by: write_line (consumed)
    #[derive(Clone, Debug)]
    pub struct Serialized(String);

    impl Serialized {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }
}

pub mod trailer_line {
    /// is_trailer_line(v)
    ///
    /// Produced by: serialize_trailer(names: &NameTable, bias: &WallNs, cpu_bias: &CpuNs) -> TrailerLine
    #[derive(Clone, Debug)]
    pub struct TrailerLine(String);

    impl TrailerLine {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }
}
}
}

// Each operation's signature is the contract the spec demands of its
// implementation; a missing or drifted fn fails to compile on the line
// naming it.
const _: fn() -> crate::Ticks = crate::read_tsc;
const _: fn() -> crate::CpuNs = crate::read_cpu_clock;
const _: fn(v: &crate::Ticks) -> crate::WallNs = crate::calibrate_to_ns;
const _: fn(end: &crate::Ticks, start: &crate::Ticks) -> crate::Ticks = crate::ticks_delta;
const _: fn(end: &crate::WallNs, start: &crate::WallNs) -> crate::WallNs = crate::wall_duration;
const _: fn(end: &crate::CpuNs, start: &crate::CpuNs) -> crate::CpuNs = crate::cpu_duration;
const _: fn(acc: &crate::WallNs, delta: &crate::WallNs) -> crate::WallNs = crate::wall_accumulate;
const _: fn(acc: &crate::CpuNs, delta: &crate::CpuNs) -> crate::CpuNs = crate::cpu_accumulate;
const _: fn(child_inclusive: &crate::WallNs) = crate::report_child_inclusive;
const _: fn(inclusive: &crate::WallNs, children_sum: &crate::WallNs) -> crate::WallNs = crate::compute_self_time;
const _: fn(exec: crate::generated::piano_runtime::async_execution::AsyncExecution) -> crate::MidPoll = crate::begin_poll;
const _: fn(exec: crate::generated::piano_runtime::async_execution::AsyncExecution) -> crate::PollCompleted = crate::mark_completed;
const _: fn(exec: &crate::generated::piano_runtime::async_execution::AsyncExecution) = crate::emit;
const _: fn(id: &crate::NameId, self_wall: &crate::WallNs, inclusive_wall: &crate::WallNs, cpu: &crate::CpuNs, alloc: &crate::AllocDelta) = crate::aggregate;
const _: fn(names: &crate::NameTable, bias: &crate::WallNs, cpu_bias: &crate::CpuNs, run_id: &String, timestamp_ms: u128) -> crate::SerializedLine = crate::serialize_header;
const _: fn(id: &crate::NameId, self_wall: &crate::WallNs, inclusive_wall: &crate::WallNs, cpu_self: &crate::CpuNs, alloc: &crate::AllocDelta, calls: u64, thread: u64) -> crate::SerializedLine = crate::serialize_aggregate;
const _: fn(id: &crate::NameId, elapsed: &crate::WallNs, depth: u32) -> crate::SerializedLine = crate::serialize_interrupted;
const _: fn(names: &crate::NameTable, bias: &crate::WallNs, cpu_bias: &crate::CpuNs) -> crate::SerializedLine = crate::serialize_trailer;
const _: fn(line: crate::SerializedLine, dest: &std::path::Path) -> Result<(), std::io::Error> = crate::write_line;
