// Code generated by carve-build. DO NOT EDIT.

// Copyright (C) 2026 Harnoor Lal
//
// This program is free software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation, version 3 of
// the License.
//
// This program is distributed in the hope that it will be
// useful, but WITHOUT ANY WARRANTY; without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
// PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public
// License along with this program.  If not, see
// <https://www.gnu.org/licenses/>.

// As a special exception, you may create a larger work that
// contains part or all of the text that carve copies from its
// own code (not from its input file) into its output files and
// distribute that work under terms of your choice, so long as
// that work isn't itself a code generator using that text or a
// modified version thereof as text that it copies into its
// output.  Alternatively, if you modify or redistribute carve
// itself, you may (at your option) remove this special
// exception, which will cause that text and the resulting
// carve output files to be licensed under the GNU General
// Public License without this special exception.
//
// This special exception was added by Harnoor Lal in version
// 0.1.0 of carve.
//
// This Exception is an additional permission under section 7
// of the GNU General Public License, version 3 ("GPLv3").

#![cfg_attr(rustfmt, rustfmt::skip)]

#[test]
fn calibrate_to_ns_is_nonnegative_wall_ns() {
    let v = crate::fixtures::calibrate_to_ns_subject();
    let value = crate::calibrate_to_ns(&v);
    assert!(crate::predicates::is_nonnegative_wall_ns(&value));
}

#[test]
fn wall_duration_is_nonnegative_wall_ns() {
    let (end, start) = crate::fixtures::wall_duration_subject();
    let value = crate::wall_duration(&end, &start);
    assert!(crate::predicates::is_nonnegative_wall_ns(&value));
}

#[test]
fn cpu_duration_is_nonnegative_cpu_ns() {
    let (end, start) = crate::fixtures::cpu_duration_subject();
    let value = crate::cpu_duration(&end, &start);
    assert!(crate::predicates::is_nonnegative_cpu_ns(&value));
}

#[test]
fn compute_self_time_is_nonnegative_wall_ns() {
    let (inclusive, children_sum) = crate::fixtures::compute_self_time_subject();
    let value = crate::compute_self_time(&inclusive, &children_sum);
    assert!(crate::predicates::is_nonnegative_wall_ns(&value));
}

#[test]
fn compute_self_time_is_le_inclusive() {
    let (inclusive, children_sum) = crate::fixtures::compute_self_time_subject();
    let value = crate::compute_self_time(&inclusive, &children_sum);
    assert!(crate::predicates::is_le_inclusive(&inclusive, &value));
}

#[test]
fn compute_delta_is_nonnegative_delta() {
    let (end, start) = crate::fixtures::compute_delta_subject();
    let value = crate::compute_delta(&end, &start);
    assert!(crate::predicates::is_nonnegative_delta(&value));
}

#[test]
fn serialize_header_is_self_contained() {
    let (names, bias, cpu_bias, run_id, timestamp_ms) = crate::fixtures::serialize_header_subject();
    let value = crate::serialize_header(&names, &bias, &cpu_bias, &run_id, timestamp_ms);
    assert!(crate::predicates::is_self_contained(&value));
}

#[test]
fn serialize_aggregate_is_self_contained() {
    let (id, self_wall, inclusive_wall, cpu_self, alloc, calls, thread) = crate::fixtures::serialize_aggregate_subject();
    let value = crate::serialize_aggregate(&id, &self_wall, &inclusive_wall, &cpu_self, &alloc, calls, thread);
    assert!(crate::predicates::is_self_contained(&value));
}

#[test]
fn serialize_interrupted_is_self_contained() {
    let (id, elapsed, depth) = crate::fixtures::serialize_interrupted_subject();
    let value = crate::serialize_interrupted(&id, &elapsed, depth);
    assert!(crate::predicates::is_self_contained(&value));
}

#[test]
fn serialize_trailer_is_self_contained() {
    let (names, bias, cpu_bias) = crate::fixtures::serialize_trailer_subject();
    let value = crate::serialize_trailer(&names, &bias, &cpu_bias);
    assert!(crate::predicates::is_self_contained(&value));
}

#[test]
fn serialize_trailer_is_dual_of_header() {
    let (names, bias, cpu_bias) = crate::fixtures::serialize_trailer_subject();
    let value = crate::serialize_trailer(&names, &bias, &cpu_bias);
    assert!(crate::predicates::is_dual_of_header(&value));
}
