// Code generated by carve-build. DO NOT EDIT.

// Copyright (C) 2026 Harnoor Lal
//
// This program is free software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation, version 3 of
// the License.
//
// This program is distributed in the hope that it will be
// useful, but WITHOUT ANY WARRANTY; without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
// PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public
// License along with this program.  If not, see
// <https://www.gnu.org/licenses/>.

// As a special exception, you may create a larger work that
// contains part or all of the text that carve copies from its
// own code (not from its input file) into its output files and
// distribute that work under terms of your choice, so long as
// that work isn't itself a code generator using that text or a
// modified version thereof as text that it copies into its
// output.  Alternatively, if you modify or redistribute carve
// itself, you may (at your option) remove this special
// exception, which will cause that text and the resulting
// carve output files to be licensed under the GNU General
// Public License without this special exception.
//
// This special exception was added by Harnoor Lal in version
// 0.1.0 of carve.
//
// This Exception is an additional permission under section 7
// of the GNU General Public License, version 3 ("GPLv3").

#![cfg_attr(rustfmt, rustfmt::skip)]

// External binding preserves the declared name for type slots.
#[allow(unused_imports)]
pub use ra_ap_syntax::SourceFile;

// External binding preserves the declared name for type slots.
#[allow(unused_imports)]
pub use ra_ap_syntax::ast::Fn;

// External binding preserves the declared name for type slots.
#[allow(unused_imports)]
pub use ra_ap_syntax::ast::StmtList;

// External binding preserves the declared name for type slots.
#[allow(unused_imports)]
pub use crate::report::load::ParsedNameTable;

// External binding preserves the declared name for type slots.
#[allow(unused_imports)]
pub use std::process::ExitStatus;

pub mod piano {

pub mod source_function {
    #[derive(Debug, Clone, PartialEq)]
    pub struct SourceFunction {
        func: super::super::Fn,
        stmt_list: super::super::StmtList,
        fn_name: String,
    }

    impl SourceFunction {
        fn new(func: super::super::Fn, stmt_list: super::super::StmtList, fn_name: String) -> Self { Self { func, stmt_list, fn_name } }
        pub fn func(&self) -> &super::super::Fn { &self.func }
        pub fn stmt_list(&self) -> &super::super::StmtList { &self.stmt_list }
        pub fn fn_name(&self) -> &str { &self.fn_name }
    }

pub mod instrumentable {
    /// is_instrumentable(v)
    ///
    /// Produced by: detect_instrumentable(func: Fn) -> Instrumentable
    /// Consumed by: apply_filter (consumed)
    #[derive(Debug)]
    pub struct Instrumentable {
        func: super::super::super::Fn,
        stmt_list: super::super::super::StmtList,
        fn_name: String,
    }

    impl Instrumentable {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(func: super::super::super::Fn, stmt_list: super::super::super::StmtList, fn_name: String) -> Self { Self { func, stmt_list, fn_name } }
        pub fn func(&self) -> &super::super::super::Fn { &self.func }
        pub fn stmt_list(&self) -> &super::super::super::StmtList { &self.stmt_list }
        pub fn fn_name(&self) -> &str { &self.fn_name }
    }
}

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(func: crate::Fn) -> crate::SourceFunction = ops::detect_instrumentable;
}

pub mod selected {
    #[derive(Debug, Clone, PartialEq)]
    pub struct Selected {
        source: super::super::piano::source_function::SourceFunction,
        name_id: u32,
    }

    impl Selected {
        fn new(source: super::super::piano::source_function::SourceFunction, name_id: u32) -> Self { Self { source, name_id } }
        pub fn source(&self) -> &super::super::piano::source_function::SourceFunction { &self.source }
        pub fn name_id(&self) -> u32 { self.name_id }
    }

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(f: crate::SourceFunction, name_id: u32) -> crate::Selected = ops::apply_filter;
}

pub mod classified_async {
    #[derive(Debug, Clone, PartialEq)]
    pub struct ClassifiedAsync {
        source: super::super::piano::source_function::SourceFunction,
        name_id: u32,
    }

    impl ClassifiedAsync {
        fn new(source: super::super::piano::source_function::SourceFunction, name_id: u32) -> Self { Self { source, name_id } }
        pub fn source(&self) -> &super::super::piano::source_function::SourceFunction { &self.source }
        pub fn name_id(&self) -> u32 { self.name_id }
    }

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(f: crate::Selected) -> crate::ClassifiedAsync = ops::classify_async;
}

pub mod classified_impl_future {
    #[derive(Debug, Clone, PartialEq)]
    pub struct ClassifiedImplFuture {
        source: super::super::piano::source_function::SourceFunction,
        name_id: u32,
    }

    impl ClassifiedImplFuture {
        fn new(source: super::super::piano::source_function::SourceFunction, name_id: u32) -> Self { Self { source, name_id } }
        pub fn source(&self) -> &super::super::piano::source_function::SourceFunction { &self.source }
        pub fn name_id(&self) -> u32 { self.name_id }
    }

pub mod instrumentable_impl_future_selected {
    /// and(is_instrumentable(v),and(is_impl_future(v),is_selected(v)))
    ///
    /// Consumed by: wrap_impl_future (observed)
    #[derive(Debug)]
    pub struct InstrumentableImplFutureSelected {
        source: super::super::super::piano::source_function::SourceFunction,
        name_id: u32,
    }

    impl InstrumentableImplFutureSelected {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(source: super::super::super::piano::source_function::SourceFunction, name_id: u32) -> Self { Self { source, name_id } }
        pub fn source(&self) -> &super::super::super::piano::source_function::SourceFunction { &self.source }
        pub fn name_id(&self) -> u32 { self.name_id }
    }
}

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(f: crate::Selected) -> crate::ClassifiedImplFuture = ops::classify_impl_future;
}

pub mod classified_sync {
    #[derive(Debug, Clone, PartialEq)]
    pub struct ClassifiedSync {
        source: super::super::piano::source_function::SourceFunction,
        name_id: u32,
    }

    impl ClassifiedSync {
        fn new(source: super::super::piano::source_function::SourceFunction, name_id: u32) -> Self { Self { source, name_id } }
        pub fn source(&self) -> &super::super::piano::source_function::SourceFunction { &self.source }
        pub fn name_id(&self) -> u32 { self.name_id }
    }

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(f: crate::Selected) -> crate::ClassifiedSync = ops::classify_sync;
}

pub mod allocator_site {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct AllocatorSite {
        start: usize,
        end: usize,
        name: String,
        type_expr: String,
        init_expr: String,
        form_gate: Option<String>,
        cfg_attr: Option<String>,
    }

    impl AllocatorSite {
        fn new(start: usize, end: usize, name: String, type_expr: String, init_expr: String, form_gate: Option<String>, cfg_attr: Option<String>) -> Self { Self { start, end, name, type_expr, init_expr, form_gate, cfg_attr } }
        pub fn start(&self) -> &usize { &self.start }
        pub fn end(&self) -> &usize { &self.end }
        pub fn name(&self) -> &str { &self.name }
        pub fn type_expr(&self) -> &str { &self.type_expr }
        pub fn init_expr(&self) -> &str { &self.init_expr }
        pub fn form_gate(&self) -> &Option<String> { &self.form_gate }
        pub fn cfg_attr(&self) -> &Option<String> { &self.cfg_attr }
    }

pub mod detected {
    /// is_detected(v)
    ///
    /// Produced by: detect_allocator(file: &SourceFile) -> Detected
    /// Consumed by: classify_cfg_gated (consumed)
    /// Consumed by: classify_unconditional (consumed)
    /// Consumed by: classify_cfg_attr_applied (consumed)
    #[derive(Debug)]
    pub struct Detected {
        start: usize,
        end: usize,
        name: String,
        type_expr: String,
        init_expr: String,
        form_gate: Option<String>,
        cfg_attr: Option<String>,
    }

    impl Detected {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(start: usize, end: usize, name: String, type_expr: String, init_expr: String, form_gate: Option<String>, cfg_attr: Option<String>) -> Self { Self { start, end, name, type_expr, init_expr, form_gate, cfg_attr } }
        pub fn start(&self) -> &usize { &self.start }
        pub fn end(&self) -> &usize { &self.end }
        pub fn name(&self) -> &str { &self.name }
        pub fn type_expr(&self) -> &str { &self.type_expr }
        pub fn init_expr(&self) -> &str { &self.init_expr }
        pub fn form_gate(&self) -> &Option<String> { &self.form_gate }
        pub fn cfg_attr(&self) -> &Option<String> { &self.cfg_attr }
    }
}

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(file: &crate::SourceFile) -> crate::AllocatorSite = ops::detect_allocator;
}

pub mod unconditional {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct Unconditional {
        site: super::super::piano::allocator_site::AllocatorSite,
    }

    impl Unconditional {
        fn new(site: super::super::piano::allocator_site::AllocatorSite) -> Self { Self { site } }
        pub fn site(&self) -> &super::super::piano::allocator_site::AllocatorSite { &self.site }
    }

pub mod detected_unconditional {
    /// and(is_detected(v),is_unconditional(v))
    ///
    /// Consumed by: wrap_unconditional (consumed)
    #[derive(Debug)]
    pub struct DetectedUnconditional {
        site: super::super::super::piano::allocator_site::AllocatorSite,
    }

    impl DetectedUnconditional {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(site: super::super::super::piano::allocator_site::AllocatorSite) -> Self { Self { site } }
        pub fn site(&self) -> &super::super::super::piano::allocator_site::AllocatorSite { &self.site }
    }
}

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(a: crate::AllocatorSite) -> crate::Unconditional = ops::classify_unconditional;
}

pub mod cfg_gated {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct CfgGated {
        site: super::super::piano::allocator_site::AllocatorSite,
    }

    impl CfgGated {
        fn new(site: super::super::piano::allocator_site::AllocatorSite) -> Self { Self { site } }
        pub fn site(&self) -> &super::super::piano::allocator_site::AllocatorSite { &self.site }
    }

pub mod cfg_gated_detected {
    /// and(is_cfg_gated(v),is_detected(v))
    ///
    /// Consumed by: wrap_cfg_gated (consumed)
    #[derive(Debug)]
    pub struct CfgGatedDetected {
        site: super::super::super::piano::allocator_site::AllocatorSite,
    }

    impl CfgGatedDetected {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(site: super::super::super::piano::allocator_site::AllocatorSite) -> Self { Self { site } }
        pub fn site(&self) -> &super::super::super::piano::allocator_site::AllocatorSite { &self.site }
    }
}

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(a: crate::AllocatorSite) -> crate::CfgGated = ops::classify_cfg_gated;
}

pub mod cfg_attr_applied {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct CfgAttrApplied {
        site: super::super::piano::allocator_site::AllocatorSite,
    }

    impl CfgAttrApplied {
        fn new(site: super::super::piano::allocator_site::AllocatorSite) -> Self { Self { site } }
        pub fn site(&self) -> &super::super::piano::allocator_site::AllocatorSite { &self.site }
    }

pub mod cfg_attr_applied_detected {
    /// and(is_cfg_attr_applied(v),is_detected(v))
    ///
    /// Consumed by: wrap_cfg_attr (consumed)
    #[derive(Debug)]
    pub struct CfgAttrAppliedDetected {
        site: super::super::super::piano::allocator_site::AllocatorSite,
    }

    impl CfgAttrAppliedDetected {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(site: super::super::super::piano::allocator_site::AllocatorSite) -> Self { Self { site } }
        pub fn site(&self) -> &super::super::super::piano::allocator_site::AllocatorSite { &self.site }
    }
}

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(a: crate::AllocatorSite) -> crate::CfgAttrApplied = ops::classify_cfg_attr_applied;
}

pub mod wrapped_allocator {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct WrappedAllocator {
        site: super::super::piano::allocator_site::AllocatorSite,
    }

    impl WrappedAllocator {
        fn new(site: super::super::piano::allocator_site::AllocatorSite) -> Self { Self { site } }
        pub fn site(&self) -> &super::super::piano::allocator_site::AllocatorSite { &self.site }
    }

pub mod detected_wrapped {
    /// and(is_detected(v),is_wrapped(v))
    ///
    /// Produced by: wrap_unconditional(a: Unconditional) -> DetectedWrapped
    /// Produced by: wrap_cfg_gated(a: CfgGated) -> DetectedWrapped
    /// Produced by: wrap_cfg_attr(a: CfgAttrApplied) -> DetectedWrapped
    #[derive(Debug)]
    pub struct DetectedWrapped {
        site: super::super::super::piano::allocator_site::AllocatorSite,
    }

    impl DetectedWrapped {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(site: super::super::super::piano::allocator_site::AllocatorSite) -> Self { Self { site } }
        pub fn site(&self) -> &super::super::super::piano::allocator_site::AllocatorSite { &self.site }
    }
}

pub mod wrapped {
    /// is_wrapped(v)
    ///
    /// Produced by: append_default_allocator() -> Wrapped
    #[derive(Debug)]
    pub struct Wrapped {
        site: super::super::super::piano::allocator_site::AllocatorSite,
    }

    impl Wrapped {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(site: super::super::super::piano::allocator_site::AllocatorSite) -> Self { Self { site } }
        pub fn site(&self) -> &super::super::super::piano::allocator_site::AllocatorSite { &self.site }
    }
}

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(a: crate::Unconditional) -> crate::WrappedAllocator = ops::wrap_unconditional;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(a: crate::CfgGated) -> crate::WrappedAllocator = ops::wrap_cfg_gated;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(a: crate::CfgAttrApplied) -> crate::WrappedAllocator = ops::wrap_cfg_attr;

    // The producer's signature is the contract the spec demands of it.
    const _: fn() -> crate::WrappedAllocator = ops::append_default_allocator;
}

pub mod function_identity {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct FunctionIdentity(String);

    impl FunctionIdentity {
        pub fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }
}

pub mod stable_identity {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct StableIdentity {
        identity: super::super::piano::function_identity::FunctionIdentity,
    }

    impl StableIdentity {
        fn new(identity: super::super::piano::function_identity::FunctionIdentity) -> Self { Self { identity } }
        pub fn identity(&self) -> &super::super::piano::function_identity::FunctionIdentity { &self.identity }
    }

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(name: &crate::FunctionIdentity) -> crate::StableIdentity = ops::store_stable_identity;
}

pub mod tag_name {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct TagName(String);

    impl TagName {
        pub(crate) fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }

pub mod valid {
    /// is_valid(v)
    ///
    /// Produced by: validate_tag(name: &TagName) -> Valid
    /// Consumed by: save_tag (observed)
    /// Consumed by: resolve_tag (observed)
    #[derive(Clone, Debug)]
    pub struct Valid(String);

    impl Valid {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }
}
}

pub mod run_id {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct RunId(String);

    impl RunId {
        pub(crate) fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }

pub mod resolved {
    /// is_resolved(v)
    ///
    /// Produced by: resolve_tag(name: &TagName, store: &std::path::Path) -> Resolved
    /// Consumed by: load_tagged_run (observed)
    #[derive(Clone, Debug)]
    pub struct Resolved(String);

    impl Resolved {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }
}
}

pub mod build_result {
    #[derive(Debug, Clone, PartialEq)]
    pub struct BuildResult {
        status: super::super::ExitStatus,
        diagnostics: String,
    }

    impl BuildResult {
        fn new(status: super::super::ExitStatus, diagnostics: String) -> Self { Self { status, diagnostics } }
        pub fn status(&self) -> &super::super::ExitStatus { &self.status }
        pub fn diagnostics(&self) -> &str { &self.diagnostics }
    }

pub mod failure {
    /// is_failure(v)
    ///
    /// Produced by: invoke_compiler() -> Failure
    /// Produced by: classify_failure(result: BuildResult) -> Failure
    /// Consumed by: report_build_failure (observed)
    #[derive(Debug)]
    pub struct Failure {
        status: super::super::super::ExitStatus,
        diagnostics: String,
    }

    impl Failure {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(status: super::super::super::ExitStatus, diagnostics: String) -> Self { Self { status, diagnostics } }
        pub fn status(&self) -> &super::super::super::ExitStatus { &self.status }
        pub fn diagnostics(&self) -> &str { &self.diagnostics }
    }
}

pub mod failure_or_success {
    /// or(is_failure(v),is_success(v))
    ///
    /// Produced by: invoke_compiler() -> FailureOrSuccess
    /// Consumed by: classify_success (consumed)
    /// Consumed by: classify_failure (consumed)
    #[derive(Debug)]
    pub struct FailureOrSuccess {
        status: super::super::super::ExitStatus,
        diagnostics: String,
    }

    impl FailureOrSuccess {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(status: super::super::super::ExitStatus, diagnostics: String) -> Self { Self { status, diagnostics } }
        pub fn status(&self) -> &super::super::super::ExitStatus { &self.status }
        pub fn diagnostics(&self) -> &str { &self.diagnostics }
    }
}

pub mod success {
    /// is_success(v)
    ///
    /// Produced by: invoke_compiler() -> Success
    /// Produced by: classify_success(result: BuildResult) -> Success
    #[derive(Debug)]
    pub struct Success {
        status: super::super::super::ExitStatus,
        diagnostics: String,
    }

    impl Success {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(status: super::super::super::ExitStatus, diagnostics: String) -> Self { Self { status, diagnostics } }
        pub fn status(&self) -> &super::super::super::ExitStatus { &self.status }
        pub fn diagnostics(&self) -> &str { &self.diagnostics }
    }
}

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn() -> Result<crate::BuildResult, std::io::Error> = ops::invoke_compiler;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(result: crate::BuildResult) -> crate::BuildResult = ops::classify_success;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(result: crate::BuildResult) -> crate::BuildResult = ops::classify_failure;
}

pub mod ndjson_line {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct NdjsonLine(String);

    impl NdjsonLine {
        pub fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }

pub mod parsed_header {
    /// is_header(v)
    ///
    /// Produced by: parse_header(line: NdjsonLine) -> ParsedHeader
    #[derive(Clone, Debug)]
    pub struct ParsedHeader(String);

    impl ParsedHeader {
        // Airlock constructor belongs to the state boundary.
        #[allow(dead_code)]
        pub(crate) fn new(inner: String) -> Self { Self(inner) }
        pub fn value(&self) -> &str { &self.0 }
    }
}
}

pub mod parsed_wall {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ParsedWall(u64);

    impl ParsedWall {
        pub(crate) fn new(inner: u64) -> Self { Self(inner) }
        pub fn value(&self) -> u64 { self.0 }
    }
}

pub mod parsed_cpu {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ParsedCpu(u64);

    impl ParsedCpu {
        pub(crate) fn new(inner: u64) -> Self { Self(inner) }
        pub fn value(&self) -> u64 { self.0 }
    }
}

pub mod parsed_id {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ParsedId(u32);

    impl ParsedId {
        pub fn new(inner: u32) -> Self { Self(inner) }
        pub fn value(&self) -> u32 { self.0 }
    }
}

pub mod parsed_alloc {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct ParsedAlloc {
        alloc_count: u64,
        alloc_bytes: u64,
        free_count: u64,
        free_bytes: u64,
    }

    impl ParsedAlloc {
        fn new(alloc_count: u64, alloc_bytes: u64, free_count: u64, free_bytes: u64) -> Self { Self { alloc_count, alloc_bytes, free_count, free_bytes } }
        pub fn alloc_count(&self) -> u64 { self.alloc_count }
        pub fn alloc_bytes(&self) -> u64 { self.alloc_bytes }
        pub fn free_count(&self) -> u64 { self.free_count }
        pub fn free_bytes(&self) -> u64 { self.free_bytes }
    }

    pub mod ops;

    // The producer's signature is the contract the spec demands of it.
    const _: fn(rec: &crate::NdjsonAggregate) -> crate::ParsedAlloc = ops::take_alloc;
}

pub mod corrected_wall {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct CorrectedWall(u64);

    impl CorrectedWall {
        pub fn new(inner: u64) -> Self { Self(inner) }
        pub fn value(&self) -> u64 { self.0 }
    }
}

pub mod corrected_cpu {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct CorrectedCpu(u64);

    impl CorrectedCpu {
        pub fn new(inner: u64) -> Self { Self(inner) }
        pub fn value(&self) -> u64 { self.0 }
    }
}

pub mod ndjson_name_table {
    #[derive(Debug, Clone, PartialEq)]
    pub struct NdjsonNameTable {
        kind: String,
        names: super::super::ParsedNameTable,
        qualified: super::super::ParsedNameTable,
    }

    impl NdjsonNameTable {
        pub fn new(kind: String, names: super::super::ParsedNameTable, qualified: super::super::ParsedNameTable) -> Self { Self { kind, names, qualified } }
        pub fn kind(&self) -> &str { &self.kind }
        pub fn names(&self) -> &super::super::ParsedNameTable { &self.names }
        pub fn qualified(&self) -> &super::super::ParsedNameTable { &self.qualified }
    }
}

pub mod ndjson_measurement {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct NdjsonMeasurement {
        span_id: u64,
        parent_span_id: u64,
        name_id: u32,
        start_ns: super::super::piano::parsed_wall::ParsedWall,
        end_ns: super::super::piano::parsed_wall::ParsedWall,
        thread_id: u64,
        cpu_start_ns: super::super::piano::parsed_cpu::ParsedCpu,
        cpu_end_ns: super::super::piano::parsed_cpu::ParsedCpu,
        alloc_count: u64,
        alloc_bytes: u64,
        free_count: u64,
        free_bytes: u64,
    }

    impl NdjsonMeasurement {
        // Constructor mirrors the product fields exactly.
        #[allow(clippy::too_many_arguments)]
        pub fn new(span_id: u64, parent_span_id: u64, name_id: u32, start_ns: super::super::piano::parsed_wall::ParsedWall, end_ns: super::super::piano::parsed_wall::ParsedWall, thread_id: u64, cpu_start_ns: super::super::piano::parsed_cpu::ParsedCpu, cpu_end_ns: super::super::piano::parsed_cpu::ParsedCpu, alloc_count: u64, alloc_bytes: u64, free_count: u64, free_bytes: u64) -> Self { Self { span_id, parent_span_id, name_id, start_ns, end_ns, thread_id, cpu_start_ns, cpu_end_ns, alloc_count, alloc_bytes, free_count, free_bytes } }
        pub fn span_id(&self) -> u64 { self.span_id }
        pub fn parent_span_id(&self) -> u64 { self.parent_span_id }
        pub fn name_id(&self) -> u32 { self.name_id }
        pub fn start_ns(&self) -> &super::super::piano::parsed_wall::ParsedWall { &self.start_ns }
        pub fn end_ns(&self) -> &super::super::piano::parsed_wall::ParsedWall { &self.end_ns }
        pub fn thread_id(&self) -> u64 { self.thread_id }
        pub fn cpu_start_ns(&self) -> &super::super::piano::parsed_cpu::ParsedCpu { &self.cpu_start_ns }
        pub fn cpu_end_ns(&self) -> &super::super::piano::parsed_cpu::ParsedCpu { &self.cpu_end_ns }
        pub fn alloc_count(&self) -> u64 { self.alloc_count }
        pub fn alloc_bytes(&self) -> u64 { self.alloc_bytes }
        pub fn free_count(&self) -> u64 { self.free_count }
        pub fn free_bytes(&self) -> u64 { self.free_bytes }
    }
}

pub mod ndjson_aggregate {
    #[derive(Debug, Clone, PartialEq, Eq)]
    pub struct NdjsonAggregate {
        thread: u64,
        name_id: u32,
        calls: u64,
        self_ns: super::super::piano::parsed_wall::ParsedWall,
        inclusive_ns: super::super::piano::parsed_wall::ParsedWall,
        cpu_self_ns: super::super::piano::parsed_cpu::ParsedCpu,
        alloc_count: u64,
        alloc_bytes: u64,
        free_count: u64,
        free_bytes: u64,
        interrupted: bool,
    }

    impl NdjsonAggregate {
        // Constructor mirrors the product fields exactly.
        #[allow(clippy::too_many_arguments)]
        pub fn new(thread: u64, name_id: u32, calls: u64, self_ns: super::super::piano::parsed_wall::ParsedWall, inclusive_ns: super::super::piano::parsed_wall::ParsedWall, cpu_self_ns: super::super::piano::parsed_cpu::ParsedCpu, alloc_count: u64, alloc_bytes: u64, free_count: u64, free_bytes: u64, interrupted: bool) -> Self { Self { thread, name_id, calls, self_ns, inclusive_ns, cpu_self_ns, alloc_count, alloc_bytes, free_count, free_bytes, interrupted } }
        pub fn thread(&self) -> u64 { self.thread }
        pub fn name_id(&self) -> u32 { self.name_id }
        pub fn calls(&self) -> u64 { self.calls }
        pub fn self_ns(&self) -> &super::super::piano::parsed_wall::ParsedWall { &self.self_ns }
        pub fn inclusive_ns(&self) -> &super::super::piano::parsed_wall::ParsedWall { &self.inclusive_ns }
        pub fn cpu_self_ns(&self) -> &super::super::piano::parsed_cpu::ParsedCpu { &self.cpu_self_ns }
        pub fn alloc_count(&self) -> u64 { self.alloc_count }
        pub fn alloc_bytes(&self) -> u64 { self.alloc_bytes }
        pub fn free_count(&self) -> u64 { self.free_count }
        pub fn free_bytes(&self) -> u64 { self.free_bytes }
        pub fn interrupted(&self) -> bool { self.interrupted }
    }
}

pub mod body_record {
    #[derive(Debug, Clone, PartialEq)]
    pub enum BodyRecord {
        Trailer {
            table: super::super::piano::ndjson_name_table::NdjsonNameTable,
        },
        Aggregate {
            agg: super::super::piano::ndjson_aggregate::NdjsonAggregate,
        },
        Measurement {
            span: super::super::piano::ndjson_measurement::NdjsonMeasurement,
        },
        Unrecognized,
    }
}
}

// Each operation's signature is the contract the spec demands of its
// implementation; a missing or drifted fn fails to compile on the line
// naming it.
const _: fn(inj: crate::source_map::StringInjector, f: &crate::ClassifiedSync) -> crate::source_map::StringInjector = crate::inject_guard;
const _: fn(inj: crate::source_map::StringInjector, f: &crate::ClassifiedAsync) -> crate::source_map::StringInjector = crate::wrap_async;
const _: fn(inj: crate::source_map::StringInjector, f: &crate::ClassifiedImplFuture) -> crate::source_map::StringInjector = crate::wrap_impl_future;
const _: fn(name: &crate::TagName) -> Result<crate::TagName, crate::error::Error> = crate::validate_tag;
const _: fn(name: &crate::TagName, run: &crate::RunId, store: &std::path::Path) -> Result<(), crate::error::Error> = crate::save_tag;
const _: fn(name: &crate::TagName, store: &std::path::Path) -> Result<crate::RunId, crate::error::Error> = crate::resolve_tag;
const _: fn(run: &crate::RunId, runs: &std::path::Path) -> Result<(), crate::error::Error> = crate::load_tagged_run;
const _: fn(result: &crate::BuildResult) = crate::report_build_failure;
const _: fn(line: crate::NdjsonLine) -> Result<crate::ParsedHeader, crate::error::Error> = crate::parse_header;
const _: fn(line: &crate::NdjsonLine) -> crate::BodyRecord = crate::classify_body_line;
const _: fn(rec: &crate::NdjsonAggregate) -> crate::ParsedWall = crate::take_self_wall;
const _: fn(rec: &crate::NdjsonAggregate) -> crate::ParsedCpu = crate::take_self_cpu;
