// Code generated by carve-build. DO NOT EDIT.

// Copyright (C) 2026 Harnoor Lal
//
// This program is free software: you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation, version 3 of
// the License.
//
// This program is distributed in the hope that it will be
// useful, but WITHOUT ANY WARRANTY; without even the implied
// warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
// PURPOSE.  See the GNU General Public License for more
// details.
//
// You should have received a copy of the GNU General Public
// License along with this program.  If not, see
// <https://www.gnu.org/licenses/>.

// As a special exception, you may create a larger work that
// contains part or all of the text that carve copies from its
// own code (not from its input file) into its output files and
// distribute that work under terms of your choice, so long as
// that work isn't itself a code generator using that text or a
// modified version thereof as text that it copies into its
// output.  Alternatively, if you modify or redistribute carve
// itself, you may (at your option) remove this special
// exception, which will cause that text and the resulting
// carve output files to be licensed under the GNU General
// Public License without this special exception.
//
// This special exception was added by Harnoor Lal in version
// 0.1.0 of carve.
//
// This Exception is an additional permission under section 7
// of the GNU General Public License, version 3 ("GPLv3").

#![cfg_attr(rustfmt, rustfmt::skip)]

#[test]
fn detect_instrumentable_is_instrumentable_sound() {
    let func = crate::fixtures::detect_instrumentable_subject();
    let value = crate::detect_instrumentable(func);
    assert!(crate::predicates::is_instrumentable_sound(&value));
}

#[test]
fn classify_async_is_coroutine_by_desugaring() {
    let f = crate::fixtures::classify_async_subject();
    let value = crate::classify_async(f);
    assert!(crate::predicates::is_coroutine_by_desugaring(&value));
}

#[test]
fn classify_impl_future_is_delegable_future() {
    let f = crate::fixtures::classify_impl_future_subject();
    let value = crate::classify_impl_future(f);
    assert!(crate::predicates::is_delegable_future(&value));
}

#[test]
fn classify_sync_is_scope_bounded() {
    let f = crate::fixtures::classify_sync_subject();
    let value = crate::classify_sync(f);
    assert!(crate::predicates::is_scope_bounded(&value));
}

#[test]
fn wrap_unconditional_is_single_global_allocator() {
    let a = crate::fixtures::wrap_unconditional_subject();
    let value = crate::wrap_unconditional(a);
    assert!(crate::predicates::is_single_global_allocator(&value));
}

#[test]
fn wrap_cfg_gated_is_cfg_gate_preserved() {
    let a = crate::fixtures::wrap_cfg_gated_subject();
    let a_witness = a.clone();
    let value = crate::wrap_cfg_gated(a);
    assert!(crate::predicates::is_cfg_gate_preserved(&a_witness, &value));
}

#[test]
fn wrap_cfg_gated_is_single_global_allocator() {
    let a = crate::fixtures::wrap_cfg_gated_subject();
    let value = crate::wrap_cfg_gated(a);
    assert!(crate::predicates::is_single_global_allocator(&value));
}

#[test]
fn wrap_cfg_attr_is_cfg_gate_preserved() {
    let a = crate::fixtures::wrap_cfg_attr_subject();
    let a_witness = a.clone();
    let value = crate::wrap_cfg_attr(a);
    assert!(crate::predicates::is_cfg_gate_preserved(&a_witness, &value));
}

#[test]
fn wrap_cfg_attr_is_single_global_allocator() {
    let a = crate::fixtures::wrap_cfg_attr_subject();
    let value = crate::wrap_cfg_attr(a);
    assert!(crate::predicates::is_single_global_allocator(&value));
}

#[test]
fn append_default_allocator_is_single_global_allocator() {
    let () = crate::fixtures::append_default_allocator_subject();
    let value = crate::append_default_allocator();
    assert!(crate::predicates::is_single_global_allocator(&value));
}

#[test]
fn parse_header_is_structurally_valid() {
    let line = crate::fixtures::parse_header_subject();
    let value = crate::parse_header(line).expect("fixture run succeeds");
    assert!(crate::predicates::is_structurally_valid(&value));
}

#[test]
fn classify_body_line_is_classification_total() {
    let line = crate::fixtures::classify_body_line_subject();
    let value = crate::classify_body_line(&line);
    assert!(crate::predicates::is_classification_total(&value));
}
