//! Embedded piano-runtime source, generated by build.rs.
//!
//! Used by the wrapper pipeline to compile piano-runtime with the user's
//! exact rustc version. The source is written to target/piano/runtime-src/
//! and compiled via `cargo build`.

include!(concat!(env!("OUT_DIR"), "/runtime_embed.rs"));

use std::path::Path;

/// Write the embedded runtime source tree to `dest_dir`.
///
/// Creates the directory structure and writes all files. Overwrites
/// existing files (idempotent). Caller should only invoke this when
/// the cache is stale or missing.
pub fn write_to_disk(dest_dir: &Path) -> std::io::Result<()> {
    for (rel_path, content) in files() {
        let dest = dest_dir.join(rel_path);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&dest, content)?;
    }
    Ok(())
}
